from simple_colors import *
print(yellow("#################################################################################"))
print(yellow("#       _______________       ______                     _              _ ___   #"))
print(yellow("#      /               \      | ___ \                   | |            | |__ \  #"))
print(yellow("#     /                 \     | |_/ /_ __ ___  __ _  ___| |__   ___  __| |  ) | #"))
print(yellow("#    /                   \    | ___ \ '__/ _ \/ _` |/ __| '_ \ / _ \/ _` | / /  #"))
print(yellow("#   /                     \   | |_/ / | |  __/ (_| | (__| | | |  __/ (_| ||_|   #"))
print(yellow("#  /_ _ _ _ _ _ _ _ _ _ _ _\  \____/|_|  \___|\__,_|\___|_| |_|\___|\__,_|(_)   #"))
print(yellow("# | \    Where Was My     / |                                                   #"))
print(yellow("# |  \      Account      /  |                                                   #"))
print(yellow("# |  /\   Info Leaked?  /\  |              Passive Reconnaissance               #"))
print(yellow("# | /  \_ _ _ _ _ _ _ _/  \ |                                                   #"))
print(yellow("# |/                       \|       Tool Created by: @Mstrmind (Instagram)      #"))
print(yellow("# |_________________________|                                                   #"))
print(yellow("#                                                                               #"))
print(yellow("#        The Creator Of This Tool Is Not Responsible For Your Actions!          #"))
print(yellow("#################################################################################"))
