from simple_colors import *
print(cyan("#################################################################################", ['bright']))
print(cyan("#       _______________       ______                     _              _ ___   #", ['bright']))
print(cyan("#      /               \      | ___ \                   | |            | |__ \  #", ['bright']))
print(cyan("#     /                 \     | |_/ /_ __ ___  __ _  ___| |__   ___  __| |  ) | #", ['bright']))
print(cyan("#    /                   \    | ___ \ '__/ _ \/ _` |/ __| '_ \ / _ \/ _` | / /  #", ['bright']))
print(cyan("#   /                     \   | |_/ / | |  __/ (_| | (__| | | |  __/ (_| ||_|   #", ['bright']))
print(cyan("#  /_ _ _ _ _ _ _ _ _ _ _ _\  \____/|_|  \___|\__,_|\___|_| |_|\___|\__,_|(_)   #", ['bright']))
print(cyan("# | \    Where Was My     / |                                                   #", ['bright']))
print(cyan("# |  \      Account      /  |                                                   #", ['bright']))
print(cyan("# |  /\   Info Leaked?  /\  |              Passive Reconnaissance               #", ['bright']))
print(cyan("# | /  \_ _ _ _ _ _ _ _/  \ |                                                   #", ['bright']))
print(cyan("# |/                       \|       Tool Created by: @Mstrmind.hack (Instagram) #", ['bright']))
print(cyan("# |_________________________|                                                   #", ['bright']))
print(cyan("#                                                                               #", ['bright']))
print(cyan("#        The Creator Of This Tool Is Not Responsible For Your Actions!          #", ['bright']))
print(cyan("#################################################################################", ['bright']))
