from simple_colors import *
print(yellow("#####################################################################"))
print(yellow("#       _____________            ____                   _    __     #"))
print(yellow("#      /             \          / __/____ __ _  ___ _  (_)  / /     #"))
print(yellow("#     /               \        / _/ /___//  ' \/ _ `/ / /  / /      #"))
print(yellow("#    /                 \      /___/     /_/_/_/\_,_/ /_/  /_/       #"))
print(yellow("#   /                   \        ___                                #"))
print(yellow("#  /_ _ _ _ _ _ _ _ _ _ _\      / _ \ ___  ____ ___   ___           #"))
print(yellow("# |\                     /|    / , _// -_)/ __// _ \ / _ \          #"))
print(yellow("# | \ Where Was         / |   /_/|_| \__/ \__/ \___//_//_/          #"))
print(yellow("# |  \   My E-mail     /  |                                         #"))
print(yellow("# |  /\       Leaked? /\  |      Passive E-mail Reconnaissance      #"))
print(yellow("# | /  \_ _ _ _ _ _ _/  \ |                                         #"))
print(yellow("# |/                     \|  Tool Created by: Mstrmind (instagram)  #"))
print(yellow("# |_______________________|                                         #"))
print(yellow("#                                                                   #"))
print(yellow("#   The Creator of this tool is not responsible for your actions!   #"))
print(yellow("#####################################################################"))
